version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:current
    resource_class: large
    steps:
      - checkout
      - run: npm install
      - run:
          command: npm run build
          name: Build app
      
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
      
