version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - run: npm install
      - run:
          command: npm run build:prod
          name: Build app
      - persist_to_workspace:
          root: ~/nodesample
          paths: .
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
      
